/**
 * JWT Constants
 */
export const JWT_CONSTANTS = {
  DEFAULT_ISSUER: 'wandermind.api',
  DEFAULT_AUDIENCE: 'wandermind.users',
  ENV_KEYS: {
    JWT_SECRET: 'JWT_SECRET',
    JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
    JWT_ISSUER: 'JWT_ISSUER',
    JWT_AUDIENCE: 'JWT_AUDIENCE',
    JWT_ACCESS_EXPIRATION: 'JWT_ACCESS_EXPIRATION',
    JWT_REFRESH_EXPIRATION: 'JWT_REFRESH_EXPIRATION',
  },
} as const;
